### PR TITLE
Fix verify boilerplate

### LINKED ISSUE #23: verify-boilerplate does not tolerate copyright lines without year
/kind bug
/assign

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

copyright lines in generated files (created by the k8s code-gen) tools don't have years.
this makes the verify boilerplate check fail.

support copyright lines without year for autogenerated files.

https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/22#issuecomment-510644042

### PR DESCRIPTION
**Pull request by SataQiu**
**What this PR does / why we need it**:
This PR fixes verify boilerplate.
1. Use the PY version of the boilerplate check from k/k
2. Change some logic of PY version to meet the requirements of our project
3. This is more reliable and flexible than the Go version, I think.

Now it can work well with autogenerated files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #23 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

/cc @neolit123 @chuckha

### CODE REVIEW

**Comment by neolit123** [comment]
> Change some logic of PY version to meet the requirements of our project

could you list/diff the PY changes?
one of the points of the PY boilerplate is that it should work everywhere. if we are changing it, something is not right and maybe we should keep the GO one.

on the PY vs GO topic, i'm fine either way, but leaving it to @chuckha on the final call.

**Comment by ncdc** [comment]
+1 to what @neolit123 wrote - we should be able to copy the boilerplate verification code verbatim from k/k. What changes did you make?

**Comment by ncdc** [comment]
Here are the changes I found:
```
diff -rwb hack/boilerplate/boilerplate.py /Users/andy/go/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.py
150c150,152
< skipped_dirs = ["third_party", ".git", "vendor", "hack/boilerplate/test"]
---
> skipped_dirs = ['Godeps', 'third_party', '_gopath', '_output', '.git', 'cluster/env.sh',
>                 "vendor", "test/e2e/generated/bindata.go", "hack/boilerplate/test",
>                 "staging/src/k8s.io/kubectl/pkg/generated/bindata.go"]
153c155
< skipped_ungenerated_files = ['hack/boilerplate/boilerplate.py']
---
> skipped_ungenerated_files = ['hack/lib/swagger.sh', 'hack/boilerplate/boilerplate.py']
209c211
<     regexs["generated"] = re.compile( '(DO NOT EDIT)|(do not modify manually)' )
---
>     regexs["generated"] = re.compile( 'DO NOT EDIT' )
```

**Comment by SataQiu** [comment]
> 
> 
> Here are the changes I found:
> 
> ```
> diff -rwb hack/boilerplate/boilerplate.py /Users/andy/go/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.py
> 150c150,152
> < skipped_dirs = ["third_party", ".git", "vendor", "hack/boilerplate/test"]
> ---
> > skipped_dirs = ['Godeps', 'third_party', '_gopath', '_output', '.git', 'cluster/env.sh',
> >                 "vendor", "test/e2e/generated/bindata.go", "hack/boilerplate/test",
> >                 "staging/src/k8s.io/kubectl/pkg/generated/bindata.go"]
> 153c155
> < skipped_ungenerated_files = ['hack/boilerplate/boilerplate.py']
> ---
> > skipped_ungenerated_files = ['hack/lib/swagger.sh', 'hack/boilerplate/boilerplate.py']
> 209c211
> <     regexs["generated"] = re.compile( '(DO NOT EDIT)|(do not modify manually)' )
> ---
> >     regexs["generated"] = re.compile( 'DO NOT EDIT' )
> ```

Yes. This is what I modified:
1. Skip the check for nonexistent files in our project.
2. Change regexs to skip the check for the controller-gen generation files.

**Comment by SataQiu** [comment]
The files generated by `controller-gen` do not contain the key word "DO NOT EDIT" but "do not modify manually". I have submitted an issue https://github.com/kubernetes-sigs/controller-tools/issues/300

**Comment by SataQiu** [comment]
> 
> 
> This looks fine to me. We don't need the bazel stuff but presumably this was copied in wholesale? Do you know why some of the Copyright lines are missing `YEAR`?

Because the generated files do not contain `YEAR`, such as:
- https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta1/zz_generated.conversion.go#L4
- https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta1/zz_generated.deepcopy.go#L4

**Comment by chuckha** [comment]
I'm cool with these changes

/approve
/assign @ncdc @detiber

**Pull request merged**
