### PR TITLE
Fix jsonpatch in go.sum

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
This should fix issues encountered when working with go modules, GOPROXY, and jsonpatch.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
I edited `hack/update-deps.sh` and added `GOPROXY=https://proxy.golang.org`

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ncdc** [comment]
@cblecker @BenTheElder is this the right thing to do?

**Comment by ncdc** [comment]
/hold
pending discussions in https://github.com/kubernetes-sigs/cluster-api/pull/1217

**Comment by ncdc** [comment]
I've updated the CAPI PR and it's in the merge queue.

/hold cancel
/assign @detiber

**Comment by ncdc** [comment]
Needs approval too - thanks!

**Comment by detiber** [comment]
oops :joy:
/approve

**Pull request merged**
