### PR TITLE
🏃Update module dependencies

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by vincepri** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1120#issuecomment-538455682

**Comment by detiber** [comment]
/lgtm
/hold
hold for @chuckha's review

**Comment by vincepri** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1169

**Comment by vincepri** [comment]
Hold on, there is another repo (CAPI) that imports the wrong version

**Pull request merged**
