### PR TITLE
:sparkles: Add lint to make test command

### PR DESCRIPTION
**Pull request by kashifest**
**What this PR does / why we need it**:
Adds lint test to make test command

### CODE REVIEW

**Comment by chuckha** [comment]
an improvement for developers for sure

/approve

**Comment by vincepri** [comment]
Pinging @ncdc, which IIRC has some thoughts around adding more pre-reqs to make targets

**Comment by chuckha** [comment]
Yes, I've got lots of thoughts too, but we should put them down in an issue first. I don't think this PR is the place to discuss broader improvements. I don't want to block this PR on us figuring out how to clean up the makefile vs hack/verify scripts problem.

**Pull request merged**
