### PR TITLE
🎉 Promote @sataqiu to a maintainer

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
@SataQiu has been an excellent reviewer and contributor to the project. I would like to promote him to a maintainer moving forward.

This will have a 1 week lazy consensus.

/hold

### CODE REVIEW

**Comment by detiber** [comment]
+1 from me

**Comment by SataQiu** [comment]
Thank you all so much for your support! @chuckha @detiber @vincepri :smile:

**Comment by fabriziopandini** [comment]
+1 
/lgtm

**Comment by chuckha** [comment]
/hold cancel

thanks for all your contributions @SataQiu !

**Pull request merged**
