### PR TITLE
Vendor in kubeadm types

### PR DESCRIPTION
**Pull request by chuckha**
Add additional json tags for controller-gen v0.2.

This also removes the Constructor as we don't really need it yet. May bring them back later.

Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR adds kubeadm types and adds missing json struct tags for controller-gen v0.2.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

/assign @vincepri 
/cc @neolit123 @rudoi

### CODE REVIEW

**Comment by chuckha** [comment]
Note: I deleted a lot of the stuff that is not strictly necessary for just the types such as the defaults.

**Comment by neolit123** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-bootstrap-provider-kubeadm/22/pull-cluster-api-bootstrap-provider-kubeadm-verify/1149410971555467270/build-log.txt

> [*] Verifying gotest...
> hack/verify-gotest.sh: line 22: header_text: command not found

**Comment by ashish-amarnath** [comment]
> [*] Verifying boilerplate...
> error validating "kubeadm/v1beta1/zz_generated.deepcopy.go": copyright line should contain exactly 5 words
>error validating "kubeadm/v1beta2/zz_generated.deepcopy.go": copyright line should contain exactly 5 words
> exit status 1

**Comment by ashish-amarnath** [comment]
`verify-boilerplate.go` seems to be missing functionality similar to https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/hack/verify_boilerplate.py#L117-L121

**Comment by neolit123** [comment]
> error validating "kubeadm/v1beta1/zz_generated.deepcopy.go": copyright line should contain exactly 5 words

sigh, technically a software copyright cannot exist without a year...
`Copyright The Kubernetes Authors.`
in fact it needs to track all years of changes and k8s is doing that wrong too.

given the files are forked and that we don't have generator checks, i'd add years over the generated files.
probably, the boiler plate check needs to tolerate these, which is wrong (as mentioned above).

**Comment by neolit123** [comment]
> verify-boilerplate.go seems to be missing functionality similar to https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/hack/verify_boilerplate.py#L117-L121

it should probably just tolerate copyright lines without years too.
i will log an issue.

and then we have to PR the change in all the repos...

**Comment by chuckha** [comment]
/hold cancel

this is ok now

**Comment by vincepri** [comment]
I'll move CAPI to this fork soon

**Pull request merged**
