### PR TITLE
Fix verify-gofmt

### LINKED ISSUE #70: hack/verify-all.sh returns success when individual tests are in error
/kind bug

**What steps did you take and what happened:**
```
$ hack/verify-gofmt.sh
diff -u controllers/kubeadmconfig_controller_reconciler_test.go.orig controllers/kubeadmconfig_controller_reconciler_test.go
--- controllers/kubeadmconfig_controller_reconciler_test.go.orig        2019-08-05 10:58:51.000000000 -0400
+++ controllers/kubeadmconfig_controller_reconciler_test.go     2019-08-05 10:58:51.000000000 -0400
@@ -53,7 +53,7 @@
                                Spec: clusterv1alpha2.MachineSpec{
                                        Bootstrap: clusterv1alpha2.Bootstrap{
                                                ConfigRef: &v1.ObjectReference{
-                                                       Kind: "KubeadmConfig",
+                                                       Kind:       "KubeadmConfig",
                                                        APIVersion: "v1alpha2",
                                                },
                                        },
diff -u controllers/kubeadmconfig_controller_test.go.orig controllers/kubeadmconfig_controller_test.go
--- controllers/kubeadmconfig_controller_test.go.orig   2019-08-05 10:58:51.000000000 -0400
+++ controllers/kubeadmconfig_controller_test.go        2019-08-05 10:58:51.000000000 -0400
@@ -77,9 +77,9 @@
                                Name:      "cfg",
                                OwnerReferences: []metav1.OwnerReference{
                                        {
-                                               Kind: "Machine",
+                                               Kind:       "Machine",
                                                APIVersion: v1alpha2.SchemeGroupVersion.String(),
-                                               Name: "my-machine",
+                                               Name:       "my-machine",
                                        },
                                },
                        },

Check failed. Please run hack/update-gofmt.sh

$ hack/verify-all.sh
[*] Verifying whitespace...
[*] Verifying spelling...
[*] Verifying boilerplate...
[*] Verifying gofmt...
[*] Verifying golint...
[*] Verifying govet...
[*] Verifying deps...
[*] Verifying gotest...
[*] Verifying build...

All verify checks passed, congrats!
```
**What did you expect to happen:**
1. CI should fail

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API version: N/A
- Cluster API Bootstrap Provider Kubeadm version: commit 9e9c21912e617025096d1c220f4cbb2816ef0b1d
- Cluster API Infrastructure Provider version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
FOUND! Thanks @ncdc for reporting this one. This has been bugging me for a while.

@neolit123 might want to be aware of this one and see if it exists elsewhere.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70

**Special notes for your reviewer**:

After this first push I am going to have to actually fix the tests here as well.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

/assign @ncdc 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ncdc** [comment]
Although I bet the CI job fails now!

**Comment by neolit123** [comment]
yep that's a bug.
will update in the etcdadm and kinder repos.

**Pull request merged**
