### PR TITLE
only print failed verfiy outputs

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR makes the output of hack/verify-all.sh more useful by only showing the output of the failed files.

Related to #35 

```release-note
NONE
```

/assign @neolit123 

<details><summary>The output</summary>

```

chuckh-a02:cluster-api-bootstrap-provider-kubeadm cha$ ./hack/verify-all.sh 
[*] Verifying whitespace...
[*] Verifying spelling...
[*] Verifying boilerplate...
[*] Verifying gofmt...
[*] Verifying golint...
[*] Verifying govet...
[*] Verifying deps...
[*] Verifying gotest...
[*] Verifying build...

Some of the verify scripts failed:
- verify-boilerplate.sh:
skipping ".github/ISSUE_TEMPLATE/bug_report.md": unsupported file type
skipping ".github/ISSUE_TEMPLATE/feature_request.md": unsupported file type
skipping ".github/PULL_REQUEST_TEMPLATE.md": unsupported file type
skipping ".gitignore": unsupported file type
skipping "CONTRIBUTING.md": unsupported file type
skipping "Dockerfile": unsupported file type
skipping "LICENSE": unsupported file type
skipping "Makefile": unsupported file type
skipping "OWNERS": unsupported file type
skipping "OWNERS_ALIASES": unsupported file type
skipping "PROJECT": unsupported file type
skipping "README.md": unsupported file type
skipping "RELEASE.md": unsupported file type
skipping "SECURITY_CONTACTS": unsupported file type
skipping "code-of-conduct.md": unsupported file type
skipping "config/certmanager/certificate.yaml": unsupported file type
skipping "config/certmanager/kustomization.yaml": unsupported file type
skipping "config/certmanager/kustomizeconfig.yaml": unsupported file type
skipping "config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml": unsupported file type
skipping "config/crd/kustomization.yaml": unsupported file type
skipping "config/crd/kustomizeconfig.yaml": unsupported file type
skipping "config/crd/patches/cainjection_in_kubeadmbootstrapconfigs.yaml": unsupported file type
skipping "config/crd/patches/webhook_in_kubeadmbootstrapconfigs.yaml": unsupported file type
skipping "config/default/kustomization.yaml": unsupported file type
skipping "config/default/manager_auth_proxy_patch.yaml": unsupported file type
skipping "config/default/manager_image_patch.yaml": unsupported file type
skipping "config/default/manager_prometheus_metrics_patch.yaml": unsupported file type
skipping "config/default/manager_webhook_patch.yaml": unsupported file type
skipping "config/default/webhookcainjection_patch.yaml": unsupported file type
skipping "config/manager/kustomization.yaml": unsupported file type
skipping "config/manager/manager.yaml": unsupported file type
skipping "config/rbac/auth_proxy_role.yaml": unsupported file type
skipping "config/rbac/auth_proxy_role_binding.yaml": unsupported file type
skipping "config/rbac/auth_proxy_service.yaml": unsupported file type
skipping "config/rbac/kustomization.yaml": unsupported file type
skipping "config/rbac/leader_election_role.yaml": unsupported file type
skipping "config/rbac/leader_election_role_binding.yaml": unsupported file type
skipping "config/rbac/role.yaml": unsupported file type
skipping "config/rbac/role_binding.yaml": unsupported file type
skipping "config/samples/kubeadm_v1alpha1_kubeadmbootstrapconfig.yaml": unsupported file type
skipping "config/webhook/kustomization.yaml": unsupported file type
skipping "config/webhook/kustomizeconfig.yaml": unsupported file type
skipping "config/webhook/manifests.yaml": unsupported file type
skipping "config/webhook/service.yaml": unsupported file type
error validating "controllers/control_plane_init_locker.go": boilerplate line 2 does not match
expected: ""
got: "Licensed under the Apache License, Version 2.0 (the \"License\");"
error validating "controllers/control_plane_init_locker_test.go": boilerplate line 2 does not match
expected: ""
got: "Licensed under the Apache License, Version 2.0 (the \"License\");"
skipping "go.mod": unsupported file type
skipping "go.sum": unsupported file type
skipping "hack/boilerplate.go.txt": unsupported file type
skipping "kubeadm/README.md": unsupported file type
exit status 1

- verify-golint.sh:
Cloning http://github.com/golang/lint in /var/folders/2p/tnmjv6hn1ws2lv1bdfh8v6zr0000gq/T/tmp.GeOQ62zM...
Building golint...
Running golint...
api/v1alpha1/kubeadmbootstrapconfig_types.go:35:6: exported type KubeadmBootstrapConfigSpec should have comment or be unexported
Found 1 lint suggestions; failing.
cloudinit/cloudinit.go:32:6: exported type BaseUserData should have comment or be unexported
Found 1 lint suggestions; failing.
cloudinit/controlplane_certs.go:21:6: exported type Certificates should have comment or be unexported
Found 1 lint suggestions; failing.
Cleaning up...

```
</details>

### CODE REVIEW

**Comment by chuckha** [comment]
Here is an easy link to a successful run as a failed run is provided in the description

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-bootstrap-provider-kubeadm/36/pull-cluster-api-bootstrap-provider-kubeadm-verify/1151527986176987136/build-log.txt

**Comment by neolit123** [comment]
/assign @ashish-amarnath 
for LGTM

**Comment by chuckha** [comment]
@neolit123 what do you mean by messy? I don't want to introduce mess. Do you have suggestions for how to improve it?

**Comment by neolit123** [comment]
the output looks good here: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-bootstrap-provider-kubeadm/36/pull-cluster-api-bootstrap-provider-kubeadm-verify/1151527986176987136/build-log.txt

**Comment by ashish-amarnath** [comment]
/lgtm
I like this output more. 🙏

**Pull request merged**
