### PR TITLE
:bug: Comment out empty patches

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
Running `kustomize build "github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm//config/default/?ref=master"` fails with error `2019/08/20 10:31:27 invalid patches from <nil>`, this fixes the error and allows for files to be properly generated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by chuckha** [comment]
interesting, is that new in kubebuilder rc.0?

/lgtm

**Comment by vincepri** [comment]
Not sure, it has never worked for me with empty patches

**Comment by chuckha** [comment]
weird, I've never hit this but it's fine to remove it if this works for you

**Comment by vincepri** [comment]
I'm using 
```
$ kustomize version
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}
```

**Comment by chuckha** [comment]
I really should be using a release

```
 kustomize version
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}
```
😂

**Pull request merged**
